export const layout = [
  { type: 'action', data: 'UNDO', width: 3, disabled: true },
  { type: 'action', data: 'REDO', width: 3 , disabled: true},
  { type: 'action', data: 'STACK', color: 'time', disabled: true},
  { type: 'action', data: 'FUNC', color: 'time' , disabled: true},
  { type: 'action', data: 'SHARE', color: 'time', disabled: true},
  { type: 'number', data: 7 },
  { type: 'number', data: 8 },
  { type: 'number', data: 9 },
  { type: 'operator', data: '*' },
  { type: 'operator', data: '/' },
  { type: 'operator', data: '&' },
  { type: 'number', data: 4 },
  { type: 'number', data: 5 },
  { type: 'number', data: 6 },
  { type: 'operator', data: '+' },
  { type: 'operator', data: '-' },
  { type: 'operator', data: '|' },
  { type: 'number', data: 1 },
  { type: 'number', data: 2 },
  { type: 'number', data: 3 },
  { type: 'operator', data: '%' },
  { type: 'operator', data: '~' },
  { type: 'operator', data: '^' },
  { type: 'number', data: '.' },
  { type: 'number', data: 0 },
  { type: 'action', data: 'BCKS', color: 'error' },
  { type: 'time', data: 't' },
  { type: 'operator', data: '<<' },
  { type: 'operator', data: '>>' },
  { type: 'action', data: 'HOLD' , disabled: true },
  { type: 'action', data: 'INS' },
  { type: 'action', data: 'DEL', color: 'error' },
  { type: 'action', data: 'LEFT', width: 3 },
  { type: 'action', data: 'RIGHT', width: 3 }
]
