export const layout = [
  { type: 'action', data: 'UNDO', key: 'u', width: 3 },
  { type: 'action', data: 'REDO', key: 'r', width: 3 },
  { type: 'action', data: 'STACK', color: 'time', disabled: true},
  { type: 'action', data: 'FUNC', color: 'time' , disabled: true},
  { type: 'action', data: 'SHARE', color: 'time', disabled: true},
  { type: 'number', data: 7, key: '7' },
  { type: 'number', data: 8, key: '8' },
  { type: 'number', data: 9, key: '9' },
  { type: 'operator', data: '*', key: '*' },
  { type: 'operator', data: '/', key: '/' },
  { type: 'operator', data: '&', key: '&' },
  { type: 'number', data: 4, key: '4' },
  { type: 'number', data: 5, key: '5' },
  { type: 'number', data: 6, key: '6' },
  { type: 'operator', data: '+', key: '+' },
  { type: 'operator', data: '-', key: '-' },
  { type: 'operator', data: '|', key: '|' },
  { type: 'number', data: 1, key: '1' },
  { type: 'number', data: 2, key: '2' },
  { type: 'number', data: 3, key: '3' },
  { type: 'operator', data: '%', key: '%' },
  { type: 'operator', data: '~', key: '~' },
  { type: 'operator', data: '^', key: '^' },
  { type: 'dot', data: '.', color: 'number', key: '.' },
  { type: 'number', data: 0, key: '0' },
  { type: 'action', data: 'BCKS', color: 'error', key: 'Backspace' },
  { type: 'time', data: 't', key: 't' },
  { type: 'operator', data: '<<', key: '<' },
  { type: 'operator', data: '>>', key: '>' },
  { type: 'action', data: 'HOLD', key: 'h'},
  { type: 'action', data: 'INS',key: 'i' },
  { type: 'action', data: 'DEL', longPress: true, color: 'error', key: 'Delete' },
  { type: 'action', data: 'LEFT', longPress: true, width: 3, key: 'ArrowLeft' },
  { type: 'action', data: 'RIGHT', longPress: true, width: 3, key: 'ArrowRight' }
]
